### ISSUE TITLE
THREE.BufferAttribute: .setArray has been removed. Use BufferGeometry .setAttribute to replace/resize attribute buffers

### ISSUE THREAD

**Issue by Nomaq** [shawn0326/three.path#1]
Greetings,

I think you have a fix for the new three js version in your repository however that update is not published in npm ? is that correct or the issue has nos been addressed yet? 
Anyway awesome library.

**Comment by shawn0326** [comment]
> Greetings,
> 
> I think you have a fix for the new three js version in your repository however that update is not published in npm ? is that correct or the issue has nos been addressed yet?
> Anyway awesome library.

I don't even know that this repository has been put into npm 😄, The code on npm must be old and the fix for the new threejs version is correct.
