### ISSUE TITLE
vue3项目，使用后设置了width固定值，但是绘制出来的线宽度有宽有窄，请问知道怎么回事吗？

### ISSUE THREAD

**Issue by small-dots** [shawn0326/three.path#13]
![image](https://github.com/shawn0326/three.path/assets/52172424/ddc0c570-b705-4680-97f6-38f63d8bd04b)

**Comment by shawn0326** [comment]
这是直角拐弯的一个算法缺陷，为了避免无限长的尖角，导致宽度不一致。目前还没有完美的解决方案，可以考虑加一点圆角避免这个问题。

**Comment by small-dots** [comment]
> 这是直角拐弯的一个算法缺陷，为了避免无限长的尖角，导致宽度不一致。目前还没有完美的解决方案，可以考虑加一点圆角避免这个问题。

加上圆角确实可以解决问题。谢谢
