### ISSUE TITLE
垂直和水平宽度不一致问题

### ISSUE THREAD

**Issue by pans0930** [shawn0326/three.path#14]
作者，您好，我这边在绘制路径时，会有水平和垂直的问题，这个会显示一个三角形，应该从哪些角度去解决这个问题
![image](https://github.com/shawn0326/three.path/assets/12636945/9a8bc171-e876-47d1-a09b-8349639dcd59)

**Comment by pans0930** [comment]
其中，up方向，我使用了
`const up = new THREE.Vector3(0, 1, 0);`

**Comment by shawn0326** [comment]
对于PathGeometry来说，的确有这个缺陷。如果设置up与不设置up，都无法达到比较好的结果，那么可能暂时没有比较好的办法。
可以尝试拆分成多段线来规避一下，不过接缝处肯定就会有断开的现象。

**Comment by pans0930** [comment]
> 对于PathGeometry来说，的确有这个缺陷。如果设置up与不设置up，都无法达到比较好的结果，那么可能暂时没有比较好的办法。 可以尝试拆分成多段线来规避一下，不过接缝处肯定就会有断开的现象。

谢谢~
