### ISSUE TITLE
使用时遇到一个问题，在index.html例子中，我发现path的宽度是根据z轴进行计算的？能够根据x轴进行计算？

### ISSUE THREAD

**Issue by ycsgis** [shawn0326/three.path#4]
1.我在使用index.html实例时，发现path的宽度是根据z轴进行计算的；现在能否添加参数让他根据x或者y轴计算path的宽度

**Comment by shawn0326** [comment]
https://github.com/shawn0326/three.path/blob/e41396229a8b2a13b521b447f1a385d5831583c5/src/PathPointList.js#L50

pathPointList.set 方法中，第四个参数可以传一个Vector3类型的up方向，表示线的“上方”。如果不传，则会根据线的方向自动计算up方向。
这意味着，path的宽度延伸方向只能通过平面约束，而不能约束在某一个轴向。因为在约束平面上，线宽度扩展的方向必须要始终保持与线的方向垂直，否则，线宽度会不均匀。
例如，如果想让线在xz方向上扩展，可以传入new THREE.Vector3(0,1,0)（我猜你只是想这样做）。

**Comment by ycsgis** [comment]
![image](https://user-images.githubusercontent.com/28531822/135229753-aa5bd3cf-d37d-4cce-ab1f-75abb309e5da.png)
1.现在可以在可是范围内显示了，但是它显示的像一堵墙，而我像要的是让他能够贴着地图，有什么变通的方法吗

**Comment by shawn0326** [comment]
> 1.现在可以在可是范围内显示了，但是它显示的像一堵墙，而我像要的是让他能够贴着地图，有什么变通的方法吗
如果是在球上，up方向应该设置为垂直于地表的方向

**Comment by ycsgis** [comment]
> 在球上，up方向应该设置为垂直于地表的方

谢谢解答，up的可选值都有什么呢，没有在文档中看明白？

**Comment by shawn0326** [comment]
> 谢谢解答，up的可选值都有什么呢，没有在文档中看明白？

接收的参数类型为null或者THREE.Vector3。vector3可以是3维空间中任意的单位向量，代表线的扩展平面所朝向的方向。
