### ISSUE TITLE
关于宽度问题不一致的问题

### ISSUE THREAD

**Issue by fffyang** [shawn0326/three.path#6]
请问一下我在pathPointList.set的时候，参数cornerSplit设置为0时，会出现宽度不一致的情况。十分明显。请问这个问题应该怎么处理呢？我试过github的demo参数调整，也存在同样的问题。我希望能做到的是可视效果上宽度一致。
![image](https://user-images.githubusercontent.com/37098927/159389421-82cb28b1-6ea0-4f13-a57a-7eaedca1b25f.png)

**Comment by shawn0326** [comment]
这个暂时还没有很好的办法，因为目前只做了尖角的方案。为了防止出现非常远的尖角，所以才限制了尖角的长度，也因此导致宽度发生了变化。

我想，如果继续优化的话，可能比较好的方式是，在角度很小的情况下，将尖角变为平角。

**Comment by fffyang** [comment]
请教一下如果我想在三维坐标系中画平面。就比如在你的path基础上，在z轴方向增加一个道路高度。有什么好的建议么？

**Comment by shawn0326** [comment]
可以在PathGeometry的基础上改改，多加一层，然后补一下侧边面。另外，也可以考虑用threejs内置的Extrude，只是threejs只能平均分段。

**Comment by fffyang** [comment]
还有一个问题请教一下。我用你的PathGeometry绘制的mesh添加到场景中的时候，鼠标射线找不到这个mesh，放大摄像机到一定程度的时候，这个mesh直接消失不见了。请问你知道这可能是什么问题吗？

**Comment by fffyang** [comment]
我发现绘制的path面点位和实际看见的地方，存在很大的偏移问题。即所见的面，和mesh面，存在偏差。请问这是怎么回事呢？

**Comment by shawn0326** [comment]
> 我用你的PathGeometry绘制的mesh添加到场景中的时候，鼠标射线找不到这个mesh，放大摄像机到一定程度的时候，这个mesh直接消失不见了。请问你知道这可能是什么问题吗？

geometry更新计算一下包围球和包围盒试试

**Comment by fffyang** [comment]
geometry更新计算一下包围球和包围盒就可以了。谢谢
